services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
    - redpanda
    - start
    - --overprovisioned
    - --smp
    - "1"
    - --memory
    - 512M
    - --reserve-memory
    - 0M
    - --node-id
    - "0"
    - --check=false
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    networks:
      - devnet
  
  redpanda-ui:
    image: redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=host.docker.internal:9092
    ports:
      - "8080:8080"
    networks:
      - devnet

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - devnet

  products-consumer:
    build: ./products-consumer
    depends_on:
      - redpanda
      - mongodb
    environment:
      KAFKA_BROKERS: redpanda:9092
      MONGO_URL: mongodb://mongodb:27017
    networks:
      - devnet

networks:
  devnet:

volumes:
  mongo_data:
